---
title: "Example analysis"
format:
  html:
    embed-resources: true
execute:
  echo: false
---

```{r}
#| output: false
library(tidyverse)
library(gtsummary)
nlsy_cols <- c("glasses", "eyesight", "sleep_wkdy", "sleep_wknd", 
							 "id", "nsibs", "samp", "race_eth", "sex", "region", 
							 "income", "res_1980", "res_2002", "age_bir")
nlsy <- read_csv(here::here("data", "raw", "nlsy.csv"), 
								 na = c("-1", "-2", "-3", "-4", "-5", "-998"),
								 skip = 1, col_names = nlsy_cols) |> 
	mutate(region_cat = factor(region, labels = c("Northeast", "North Central", "South", "West")),
				 sex_cat = factor(sex, labels = c("Male", "Female")),
				 race_eth_cat = factor(race_eth, labels = c("Hispanic", "Black", "Non-Black, Non-Hispanic")),
				 eyesight_cat = factor(eyesight, labels = c("Excellent", "Very good", "Good", "Fair", "Poor")),
				 glasses_cat = factor(glasses, labels = c("No", "Yes"))) 
```

```{r}
new_table_function <- function(model, tidy_fun = broom.helpers::tidy_with_broom_or_parameters) {
	tbl_regression(
		model,
		exponentiate = TRUE,
		label = list(
			sex_cat ~ "Sex",
			eyesight_cat ~ "Eyesight"
		),
		tidy_fun = tidy_fun
	)
}
```

# Analysis

We fit three models in R. The poisson regression used robust standard errors.
```{r}
logistic_model <- glm(glasses ~ eyesight_cat + sex_cat,
											data = nlsy, family = binomial()
)
poisson_model <- glm(nsibs ~ eyesight_cat + sex_cat,
										 data = nlsy, family = poisson()
)
logbinomial_model <- glm(glasses ~ eyesight_cat + sex_cat,
												 data = nlsy, family = binomial(link = "log")
)
```

# Results

@tbl-logistic contains results from the logistic regression. @tbl-poisson contains results from the poisson regression. @tbl-logbinomial contains results from the logbinomial regression. 
```{r}
#| label: tbl-logistic
#| tbl-cap: "Logistic regression"
new_table_function(logistic_model)
```

```{r}
#| label: tbl-poisson
#| tbl-cap: "Poisson regression"
#| message: false
new_table_function(poisson_model, tidy_fun = partial(tidy_robust, vcov = "HC1"))
```

```{r}
#| label: tbl-logbinomial
#| tbl-cap: "Log-binomial regression"
new_table_function(logbinomial_model)
```
